name: nexo_app
description: "Nexo - Workforce management app (mobile + desktop)"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  dio: ^5.7.0
  go_router: ^18.0.0
  flutter_secure_storage: 10.1.0
  flutter_map: ^8.3.2
  latlong2: ^0.10.1
  intl: ^0.20.3
  socket_io_client: ^3.1.6
  geolocator: ^14.0.3
  share_plus: ^13.3.0
  connectivity_plus: ^7.3.1
  hive_flutter: ^1.1.0
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mocktail: ^1.0.4

flutter:
  uses-material-design: true